[project]
name = "openpyxl-table-formatter"
version = "0.1.0"
description = "A simple package to help export pandas DataFrame to Excel files"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
]
